export const ACTIVE_LOGIN_PLATE = "ACTIVE_LOGIN_PLATE";
export const HEADER_ACTIVE = "HEADER_ACTIVE";
export const ACTIVE_LOGIN_PAGE = "ACTIVE_LOGIN_PAGE";
export const GET_ROOM_COUNT = "GET_ROOM_COUNT";
export const CHECK_IN = "CHECK_IN";
export const CURRENT_TAB = "CURRENT_TAB";
export const MODAL_PROPS = "MODAL_PROPS";
